### ISSUE TITLE
Stray "as" should be deleted

### ISSUE THREAD

**Issue by enEin100** [hunter-college-ossd-fall-2019/kkhan01-weekly#1]
4th post, 4th paragraph, second to last sentence

**Comment by khinshankhan** [comment]
I'm afraid I don't quite see it. Feel free to make a PR fixing it though.

**Comment by enEin100** [comment]
"Here, I probably hit this problem due to the assignment as because we were all looking for the same issue."

Something about the "as" being there just felt odd, especially since the sentence would be perfectly fine without it. Not sure now if this is just a preference thing or not, so I don't want to take things as far as a pull request. Feel free to close the issue if you feel there is no issue.

**Comment by khinshankhan** [comment]
Oh, I see it now. You're absolutely right. Thanks
